name: Build and Push Python Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the pull request
    - name: Check out the code
      uses: actions/checkout@v2

    # Log in to DockerHub using secrets (username and password stored in GitHub secrets)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Set up Docker Buildx (optional, but improves Docker build performance)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up future builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build and Push Docker image for Python server
    - name: Build and Push Python Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-server:pr-${{ github.event.pull_request.number }} ./python-server
        docker push ${{ secrets.DOCKER_USERNAME }}/python-server:pr-${{ github.event.pull_request.number }}
