name: Build and Push Node.js Image on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-push-nodejs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Node.js Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-server:latest ./nodejs-server
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-server:latest